# Site settings
title: Visit Napoli
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A few pages with suggestions collected over the years
  for friends who wanted to visit Napoli.
baseurl: /VisitNapoli
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ozagordi
# Build settings
markdown: kramdown
